<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>disable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>sevencat.ruoyi</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="11.0.2" />
        <PackageReference Include="dotenv.net" Version="4.1.0" />
        <PackageReference Include="Hangfire.AspNetCore" Version="1.8.25" />
        <PackageReference Include="Hangfire.Console" Version="1.4.3" />
        <PackageReference Include="Hangfire.MemoryStorage" Version="1.8.1.2" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12"/>
        <PackageReference Include="NLog.Extensions.Logging" Version="6.2.0" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.16.16" />
        <PackageReference Include="Sevencat.Autofac.Annotation" Version="1.0.7" />
        <PackageReference Include="sevencat.common" Version="1.0.9" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Controllers\" />
    </ItemGroup>

</Project>
